### ISSUE TITLE
IndexOutOfRangeException

### ISSUE THREAD

**Issue by MrJoe** [Vodurden/Http-Multipart-Data-Parser#35]
Hi,

Sometimes we get an IndexOutOfRange exception. Unfortunately I don't have much info at the moment on what the actual input is.

```
at HttpMultipartParser.StreamingMultipartFormDataParser.<>c.<ParseSection>b__38_2(String[] x)  
at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
at HttpMultipartParser.StreamingMultipartFormDataParser.ParseSection(RebufferableBinaryReader reader)
at HttpMultipartParser.StreamingMultipartFormDataParser.Parse(RebufferableBinaryReader reader)
at HttpMultipartParser.StreamingMultipartFormDataParser.Run()
```

**Comment by Vodurden** [comment]
Hi MrJoe.

There's not a lot I can do with this report. However a few `IndexOutOfRange` exceptions have been reported and fixed over the last few months. Are you using the latest version of the library?

**Comment by MrJoe** [comment]
Latest from nuget, 2.1.1.

I assume the problem is here:
```
 Dictionary<string, string> values = SplitBySemicolonIgnoringSemicolonsInQuotes(line)
                    .Select(x => x.Split(new[] {':', '='}, 2))
                    // Limit split to 2 splits so we don't accidently split characters in file paths.
                    .ToDictionary(
                        x => x[0].Trim().Replace("\"", string.Empty).ToLower(),
                        x => x[1].Trim().Replace("\"", string.Empty));
```

If the x.Split only returns 1 element, this would match the exception I get. I'll try to get some more info.

**Comment by Vodurden** [comment]
That matches some of the other errors I've seen. If you could get me a representative multipart input then I should be able to find and fix the issue. :)

**Comment by MrJoe** [comment]
Not sure if related, but although I have 2.1.1 nuget package, the assembly version actually told me it was 1.1.5.0.

**Comment by Vodurden** [comment]
Hmm that's odd. As far as I can tell the Assembly Version *should* be `2.1.1`. If it's an older version that would certainly explain the behavior.

**Comment by BaileyDan** [comment]
I was using this at work, and I believe I have found the problem and quite frankly I was perplexed for ages so when I got home from work today I had to jump on and fix it! :).  It occurs when obtaining the content if there are multiple items separated by a semi colon and then it is finished with a semi colon i.e. "Content-Type:text/plain;boundry:--****;" for example.  This causes the SplitBySemicolonIgnoringSemicolonsInQuotes to return an empty string (or in my case a space in a string because there was also a space on the end) which when split by ":" or "=" means there is no value in the second part of the array.
I am going to request a pull for a possible fix in SplitBySemicolonIgnoringSemicolonsInQuotes which basically trims the line of any spaces and then checks the last character for ";" and if it is a ";" it substrings the line removing the last character.
I have also updated the first test to include a semicolon on the end of the first line, if you remove my code and run the tests with this there you will see one fails.
You may of course think of a better way to achieve it but just my two cents.

**Comment by BaileyDan** [comment]
p.s. this should also solve bug number #36 I believe from the code posted by them there is a ";" on the end of their content lines.

**Comment by Vodurden** [comment]
Thanks @BaileyDan!

The pull request has been merged in and I've pushed version `2.1.2` of the library to NuGet with a fix.

@MrJoe: Could you try version `2.1.2` and let me know if that fixes the issue? Thanks!

**Comment by MrJoe** [comment]
Yes will do, but this error doesn't occur very frequently. Last week it didn't occur at all.

**Comment by BaileyDan** [comment]
Thinking about this stiIl today and i think there is a better solution here. As this only solves a semicolon problem. Doesn't actually resolve if there is only one part to the split. In theory if someone was adding random stuff to their header (why i do not know but people do do funny things) you could get this problem still. I am going to look at it again over the weekend if I have any success I'll put in a pull again. :)

**Comment by BaileyDan** [comment]
Right, think I've come up with a solution that will work for all cases (no matter where in the string) that does not confirm to a valid key pair solution.
Basically, added a .Where statement after the split which only allows it through if the length is equal to two (meaning a valid key pair) otherwise, it'll be ignored. I'll request a pull, but I'll let you decide which is the best solution for yourself :+1:

**Comment by Vodurden** [comment]
I've merged the proposed changes in under version `2.1.3`. Give it a go and let me know if the problem re-occurs. See: https://github.com/Vodurden/Http-Multipart-Data-Parser/pull/38 for more details :+1:

**Comment by MrJoe** [comment]
OK, So I have been running a self built 2.1.1 for a few months without problems. It starts to look like there is an issue with the nuget package, the latest version still has 1.1.5.0 as its file version.

To confirm I have compared the 2.1.1 packaged dll with the 2.1.3 dll and they have the same sha1sum

`$ sha1sum.exe packages/HttpMultipartParser.2.1.1/lib/net40/HttpMultipartParser.dll
3a2e476bf0fb4927bc9919f8c601260cccdd1b08 packages/HttpMultipartParser.2.1.1/lib/net40/HttpMultipartParser.dll`

`$ sha1sum.exe packages/HttpMultipartParser.2.1.3/lib/net40/HttpMultipartParser.dll
3a2e476bf0fb4927bc9919f8c601260cccdd1b08 packages/HttpMultipartParser.2.1.3/lib/net40/HttpMultipartParser.dll`

**Comment by Vodurden** [comment]
@MrJoe: Good catch! I had a silly mistake in how I built the last package. I've just pushed 2.1.4 which has no changes other then it should be a real release. Thanks :+1:

**Comment by MrJoe** [comment]
Unfortunately still errors. Stack trace is different though:
```
   at HttpMultipartParser.StreamingMultipartFormDataParser.CalculateNewlineLength(Byte[]& data, Int32 offset)
   at HttpMultipartParser.StreamingMultipartFormDataParser.ParseFilePart(Dictionary`2 parameters, RebufferableBinaryReader reader)
   at HttpMultipartParser.StreamingMultipartFormDataParser.ParseSection(RebufferableBinaryReader reader)
   at HttpMultipartParser.StreamingMultipartFormDataParser.Parse(RebufferableBinaryReader reader)
   at HttpMultipartParser.StreamingMultipartFormDataParser.Run()
```

I don't have the actual content of the request.
